"""
Pre-loaded government and examination document specifications for DocReady AI.
"""

from typing import Dict, Any, List

GOVERNMENT_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "passport_india": {
        "id": "passport_india",
        "name": "Indian Passport Photo",
        "category": "Passport & Visa",
        "doc_type": "photo",
        "width_px": 413,
        "height_px": 531,
        "width_cm": 3.5,
        "height_cm": 4.5,
        "aspect_ratio": "3.5:4.5",
        "min_kb": 20,
        "max_kb": 100,
        "dpi": 300,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "Standard 3.5cm x 4.5cm photo with plain white background, 20KB-100KB."
    },
    "visa_us": {
        "id": "visa_us",
        "name": "US Visa Photo (2x2 inch)",
        "category": "Passport & Visa",
        "doc_type": "photo",
        "width_px": 600,
        "height_px": 600,
        "width_cm": 5.1,
        "height_cm": 5.1,
        "aspect_ratio": "1:1",
        "min_kb": 30,
        "max_kb": 240,
        "dpi": 300,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "Square 2in x 2in (600x600 px) photo with off-white/white background."
    },
    "upsc_photo": {
        "id": "upsc_photo",
        "name": "UPSC Photo with Name & Date",
        "category": "Exam Forms",
        "doc_type": "photo",
        "width_px": 350,
        "height_px": 350,
        "width_cm": 3.5,
        "height_cm": 3.5,
        "aspect_ratio": "1:1",
        "min_kb": 20,
        "max_kb": 300,
        "dpi": 300,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "Square photo (min 350x350 px), 20KB-300KB file size."
    },
    "upsc_signature": {
        "id": "upsc_signature",
        "name": "UPSC Signature",
        "category": "Exam Forms",
        "doc_type": "signature",
        "width_px": 350,
        "height_px": 350,
        "width_cm": 6.0,
        "height_cm": 2.0,
        "aspect_ratio": "3:1",
        "min_kb": 20,
        "max_kb": 300,
        "dpi": 300,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "Black/Blue ink signature on white background, 20KB-300KB."
    },
    "ssc_photo": {
        "id": "ssc_photo",
        "name": "SSC Exam Photo",
        "category": "Exam Forms",
        "doc_type": "photo",
        "width_px": 413,
        "height_px": 531,
        "width_cm": 3.5,
        "height_cm": 4.5,
        "aspect_ratio": "3.5:4.5",
        "min_kb": 20,
        "max_kb": 50,
        "dpi": 200,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "3.5cm x 4.5cm photo without spectacles or cap, 20KB-50KB."
    },
    "ssc_signature": {
        "id": "ssc_signature",
        "name": "SSC Signature",
        "category": "Exam Forms",
        "doc_type": "signature",
        "width_px": 472,
        "height_px": 236,
        "width_cm": 4.0,
        "height_cm": 2.0,
        "aspect_ratio": "2:1",
        "min_kb": 10,
        "max_kb": 20,
        "dpi": 200,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "Running hand signature, 4.0cm x 2.0cm, 10KB-20KB."
    },
    "pan_card_doc": {
        "id": "pan_card_doc",
        "name": "PAN Card Proof Document",
        "category": "Government ID",
        "doc_type": "scanned_doc",
        "width_px": 1240,
        "height_px": 1754,
        "width_cm": 21.0,
        "height_cm": 29.7,
        "aspect_ratio": "A4",
        "min_kb": 50,
        "max_kb": 300,
        "dpi": 200,
        "background": "white",
        "formats": ["PDF", "JPG"],
        "description": "Clear scanned document in PDF or JPG, under 300KB."
    },
    "aadhaar_card_doc": {
        "id": "aadhaar_card_doc",
        "name": "Aadhaar Card Document",
        "category": "Government ID",
        "doc_type": "scanned_doc",
        "width_px": 1240,
        "height_px": 1754,
        "width_cm": 21.0,
        "height_cm": 29.7,
        "aspect_ratio": "A4",
        "min_kb": 100,
        "max_kb": 2000,
        "dpi": 200,
        "background": "white",
        "formats": ["PDF"],
        "description": "Self-attested e-Aadhaar PDF under 2MB."
    },
    "banking_ibps_photo": {
        "id": "banking_ibps_photo",
        "name": "IBPS / SBI Bank PO Photo",
        "category": "Exam Forms",
        "doc_type": "photo",
        "width_px": 200,
        "height_px": 230,
        "width_cm": 4.5,
        "height_cm": 3.5,
        "aspect_ratio": "4.5:3.5",
        "min_kb": 20,
        "max_kb": 50,
        "dpi": 200,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "Dimensions 200 x 230 pixels, size strictly 20KB-50KB."
    },
    "gate_photo": {
        "id": "gate_photo",
        "name": "GATE / IIT Exam Photo",
        "category": "Exam Forms",
        "doc_type": "photo",
        "width_px": 480,
        "height_px": 640,
        "width_cm": 3.5,
        "height_cm": 4.5,
        "aspect_ratio": "3.5:4.5",
        "min_kb": 50,
        "max_kb": 200,
        "dpi": 300,
        "background": "white",
        "formats": ["JPG", "JPEG"],
        "description": "Aspect ratio 3.5cm x 4.5cm, 50KB to 200KB."
    }
}

def get_all_templates() -> List[Dict[str, Any]]:
    return list(GOVERNMENT_TEMPLATES.values())

def get_template_by_id(template_id: str) -> Dict[str, Any]:
    return GOVERNMENT_TEMPLATES.get(template_id, GOVERNMENT_TEMPLATES["passport_india"])
